apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: yonseiwinettest/server-image-yolov5
        #command: ["/bin/bash", "-c","while true; do sleep 1000; done"]
        command: ["/bin/bash","-c", "apt-get update && git clone https://github.com/tat1218/YOLOv5_testbed.git && cd YOLOv5_testbed && python3 server.py --rank 0 --start 10"]
        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: server-ip-service
spec:
  clusterIP: 10.96.0.200
  ports:
  - name: pytorch-ddp-port
    port: 30000
  selector:
    app: server

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-camera
  labels:
    app: smart_camera
spec:
  selector:
    matchLabels:
      app: smart-camera
  template:
    metadata:
      labels:
        app: smart-camera
    spec:
      nodeSelector:
        kubernetes.io/hostname: wnlab-nano-001
      containers:
      - name: smart-camera
        image: yonseiwinettest/smart-camera-image-yolov5
        env:
        - name: MASTER_ADDR
          value: "10.96.0.200"
        - name: MASTER_PORT
          value: "30000"
        #command: ["/bin/bash","-c","while true; do sleep 1000; done"]
        command: ["/bin/bash","-c", "apt-get update && git clone https://github.com/tat1218/YOLOv5_testbed.git && cd YOLOv5_testbed && python3.8 camera.py --rank 1 --end 10"]

        ports:
        - containerPort: 30000

---

apiVersion: v1
kind: Service
metadata:
  name: smart-camera-ip-service
spec:
  clusterIP: 10.96.0.201
  ports:
  - port: 30000
  selector:
    app: smart-camera
